In [ ]:
# Pandas Basics
In this notebook, I learn the fundamentals of Pandas, one of the most popular Python libraries for data analysis.

## Topics
- What is Pandas?
- Series
- DataFrame
- Creating Series
- Creating DataFrames
- Basic Attributes

In [ ]:
For importing pandas:

import pandas as pd

In [ ]:
# Pandas
is a Python library used for data manipulation and analysis

It provides two main data structures:

- Series (one-dimensional)
- DataFrame (two-dimensional)

In [ ]:
# Series
A Series is a one-dimensional labeled array

In [2]:
import pandas as pd 

numbers = pd.Series([10,20,30,40,50])
numbers

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# Access Elements 
as we used to

In [3]:
import pandas as pd 

numbers = pd.Series([10,20,30,40,50])
numbers[3]

np.int64(40)

In [ ]:
# series attributes
numbers.shape --> (rows, columns)
numbers.size --> number of elements 
numbers.dtype --> type of the data

In [4]:
import pandas as pd 

numbers = pd.Series([10,20,30,40,50])
numbers.shape

(5,)

In [5]:
import pandas as pd 

numbers = pd.Series([10,20,30,40,50])
numbers.size

5

In [6]:
import pandas as pd 

numbers = pd.Series([10,20,30,40,50])
numbers.dtype

dtype('int64')

In [ ]:
# Creating a DataFrame
A DataFrame is a two-dimensional table with rows and columns.

In [7]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)

df

   Name  Age  Grade
0   Ali   20     90
1  Sara   21     85
2  Omar   19     95

In [8]:
import pandas as pd

coutries = {
    "Name": ["Italy", "Egypt", "USA"],
    "Captilal": ["Roma", "Cairo", "Washington"]
}

x = pd.DataFrame(coutries)
x

    Name    Captilal
0  Italy        Roma
1  Egypt       Cairo
2    USA  Washington

In [ ]:
# DataFrame Attributes

df.shape
df.size
df.columns
df.index
df.dtypes

In [9]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df.shape

(3, 3)

In [10]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df.size

9

In [11]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df.columns

Index(['Name', 'Age', 'Grade'], dtype='object')

In [12]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df.dtypes

Name     object
Age       int64
Grade     int64
dtype: object

In [17]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df["Name"]

0     Ali
1    Sara
2    Omar
Name: Name, dtype: object

In [18]:
students = {
    "Name": ["Ali", "Sara", "Omar"],
    "Age": [20, 21, 19],
    "Grade": [90, 85, 95]
}

df = pd.DataFrame(students)
df[["Name", "Grade"]]

   Name  Grade
0   Ali     90
1  Sara     85
2  Omar     95

In [19]:
# Creating a DataFrame from Lists
import pandas as pd

names = ["Basmala", "Sara", "MO"]
grades = [90, 80, 65]
ages = [19, 20, 18]

df = pd.DataFrame ({
    "Names": names,
    "Grades": grades,
    "Ages": ages,
})

df

     Names  Grades  Ages
0  Basmala      90    19
1     Sara      80    20
2       MO      65    18

In [ ]:
## Summary

In this notebook, I learned:

- What Pandas is
- What a Series is
- What a DataFrame is
- How to create a Series
- How to create a DataFrame
- DataFrame attributes
- Selecting columns