In [ ]:
# Reading & Exploring Data

In this notebook, I learn how to load datasets into Pandas and explore them before performing any analysis.

## Topics
- read_csv()
- head()
- tail()
- sample()
- shape
- columns
- index
- dtypes
- info()
- describe()

In [4]:
import pandas as pd

df = pd.read_csv("students.CSV")
df

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [ ]:
What have I done?

I created a CSV file in Visual Studio by opening the ML Journey folder and creating this file in the pandas folder
Then I opened it using read_csv("file_name.CSV")
and call this variable

There is another way to create this file manually

import pandas as pd

students = {
    "Name": ["Ali", "Sara", "Omar", "Mona", "Youssef"],
    "Age": [20, 21, 19, 22, 20],
    "Grade": [90, 85, 95, 88, 91],
    "City": ["Alexandria", "Cairo", "Giza", "Alexandria", "Cairo"]
}

df = pd.DataFrame(students)

df.to_csv("students.csv", index=False)

Now, Let's continue :)

In [5]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.head() 
# to display rows

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [6]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.head(3)
# to display the first 3 rows

   Name  Age  Grade        City
0   Ali   20     90  Alexandria
1  Sara   21     85       Cairo
2  Omar   19     95        Giza

In [7]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.tail()
# to display last rows

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [8]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.tail(2)
# to display the last 2 rows

      Name  Age  Grade        City
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [9]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.sample()
# to display random sample

   Name  Age  Grade   City
1  Sara   21     85  Cairo

In [10]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.sample(3)
# to display 3 random rows

   Name  Age  Grade        City
2  Omar   19     95        Giza
3  Mona   22     88  Alexandria
0   Ali   20     90  Alexandria

In [11]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.shape
# to display (rows, columns)

(5, 4)

In [12]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.columns
# to display columns only

Index(['Name', 'Age', 'Grade', 'City'], dtype='object')

In [13]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.index
# the output means:
# start=0 --> the first row label = 0
# stop=5 --> it goes up to 4 (Python stops before 5)
# step=1 --> it increases by 1
# so the row labels are : 0 1 2 3 4

RangeIndex(start=0, stop=5, step=1)

In [14]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.dtypes 
# to display the data type

Name     object
Age       int64
Grade     int64
City     object
dtype: object

In [16]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.info()
# It displays:
# Number of rows
# Number of columns
# Missing values
# Data types
# Memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Grade   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [18]:
import pandas as pd

df = pd.read_csv("students.CSV")
df.describe()
# Shows statistics for numeric columns:
# count
# mean
# std
# min
# max
# 25%
# 50%
# 75%

             Age      Grade
count   5.000000   5.000000
mean   20.400000  89.800000
std     1.140175   3.701351
min    19.000000  85.000000
25%    20.000000  88.000000
50%    20.000000  90.000000
75%    21.000000  91.000000
max    22.000000  95.000000

In [ ]:
## Summary

In this notebook, I learned how to:

- Read CSV files using `read_csv()`
- Display the first and last rows
- Display random samples
- Inspect dataset dimensions
- View column names
- Check data types
- Explore dataset information
- Generate statistical summaries