In [ ]:
# Selecting & Filtering Data

In this notebook, I learn how to select rows and columns, filter data using conditions, and sort datasets in Pandas.

## Topics
- Selecting columns
- Selecting rows
- loc
- iloc
- Boolean Indexing
- Sorting
- value_counts()

In [1]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [2]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.loc[0]
# loc selects rows by their labels (index)

Name            Ali
Age              20
Grade            90
City     Alexandria
Name: 0, dtype: object

In [4]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.loc[[0,2,3]]
# to display multiple rows by loc

   Name  Age  Grade        City
0   Ali   20     90  Alexandria
2  Omar   19     95        Giza
3  Mona   22     88  Alexandria

In [5]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.iloc[0]

Name            Ali
Age              20
Grade            90
City     Alexandria
Name: 0, dtype: object

In [8]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.iloc[0:3, 1:3]
# 0:3 --> from row 0 to 2
# 1:3 --> from column 1 to 2

   Age  Grade
0   20     90
1   21     85
2   19     95

In [ ]:
loc → selects by label (index name)
iloc → selects by position (row/column number)

In [10]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df[df["Grade"]> 90]

      Name  Age  Grade   City
2     Omar   19     95   Giza
4  Youssef   20     91  Cairo

In [14]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df[df["Age"]<21]

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
2     Omar   19     95        Giza
4  Youssef   20     91       Cairo

In [15]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df[df["City"]== "Cairo"]

      Name  Age  Grade   City
1     Sara   21     85  Cairo
4  Youssef   20     91  Cairo

In [17]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df[(df["Grade"]> 85) & (df["Age"]< 21)]
# multiple conditions with & (and)

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
2     Omar   19     95        Giza
4  Youssef   20     91       Cairo

In [19]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df[(df["City"] == "Cairo") | (df["Grade"]> 90)]
# multiple conditions with | (OR)

      Name  Age  Grade   City
1     Sara   21     85  Cairo
2     Omar   19     95   Giza
4  Youssef   20     91  Cairo

In [21]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.sort_values("Grade")
# to display the grades in an ascending order

      Name  Age  Grade        City
1     Sara   21     85       Cairo
3     Mona   22     88  Alexandria
0      Ali   20     90  Alexandria
4  Youssef   20     91       Cairo
2     Omar   19     95        Giza

In [23]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.sort_values("Grade", ascending = False)
# to display the grades in a descending order

      Name  Age  Grade        City
2     Omar   19     95        Giza
4  Youssef   20     91       Cairo
0      Ali   20     90  Alexandria
3     Mona   22     88  Alexandria
1     Sara   21     85       Cairo

In [24]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.sort_values("Age")

      Name  Age  Grade        City
2     Omar   19     95        Giza
0      Ali   20     90  Alexandria
4  Youssef   20     91       Cairo
1     Sara   21     85       Cairo
3     Mona   22     88  Alexandria

In [26]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df["City"].value_counts()
# to count values

City
Alexandria    2
Cairo         2
Giza          1
Name: count, dtype: int64

In [27]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df["Grade"].value_counts()
# to count values

Grade
90    1
85    1
95    1
88    1
91    1
Name: count, dtype: int64

In [ ]:
## Summary

In this notebook, I learned how to:

- Select one or multiple columns
- Select rows using `loc`
- Select rows using `iloc`
- Filter data using Boolean Indexing
- Sort data using `sort_values()`
- Count values using `value_counts()`