In [ ]:
# Cleaning Data

In this notebook, I learn how to clean datasets by handling missing values, removing duplicates, renaming columns, and changing data types.

## Topics
- Missing Values
- isna()
- dropna()
- fillna()
- Duplicates
- drop_duplicates()
- rename()
- astype()

In [1]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [ ]:
1) If I want to check if there is any missing values 
---> df.isna()

In [2]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.isna()

    Name    Age  Grade   City
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [ ]:
This returns a DataFrame of True and False
True → Missing value
False → Value exists

In [ ]:
2) To count the missing values 
---> df.isna().sum()

In [3]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.isna().sum()

Name     0
Age      0
Grade    0
City     0
dtype: int64

In [ ]:
3) If I want to remove the rows that contain missing values 
---> df.dropna()

In [4]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.dropna()

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [6]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df = df.isna()
# to save the result

In [ ]:
4) To fill the missing values instead of removing 
---> df["column's name"].fillna(df["column's name"].mean())

In [7]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df = df["Grade"].fillna(df["Grades"].mean())
# .mean() ---> to will missing grades with mean 
# There are no missing values, so it raises an error

KeyError: 'Grades'

In [9]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df["City"] = df["City"].fillna("Unknowns")
# fill the missing values in city column by unknown

In [ ]:
5) Check for duplicates 
---> df.duplicated()

In [10]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
Returns:
True → Duplicate row
False → Unique row

In [ ]:
6) To count duplicates:
---> df.duplicated().sum()

In [ ]:
7) To remove duplicates:
---> df = df.drop_duplicates()

In [ ]:
8) To rename columns:
---> df = df.rename(columns={
    "old column's name": "New name"
})
Before, I have:   Name  Age  Grade

In [12]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df = df.rename(columns={
    "Grade": "Final Grade"
})
df

      Name  Age  Final Grade        City
0      Ali   20           90  Alexandria
1     Sara   21           85       Cairo
2     Omar   19           95        Giza
3     Mona   22           88  Alexandria
4  Youssef   20           91       Cairo

In [ ]:
9) To change data type 
---> a) check the data type first by df.dtypes
b) convert:
df["Column's name"] = df["the same column's name"].astype(data type I want)

In [14]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df.dtypes

Name     object
Age       int64
Grade     int64
City     object
dtype: object

In [17]:
import pandas as pd 

df = pd.read_csv("students.CSV")
df["Age"] = df["Age"].astype(float)
df.dtypes

Name      object
Age      float64
Grade      int64
City      object
dtype: object

In [ ]:
# Tips:

- isna() checks for missing values

- dropna() removes missing values

- fillna() replaces missing values

- duplicated() finds duplicates

- drop_duplicates() removes duplicates

- rename() changes column names

- astype() changes the data type of a column

In [ ]:
## Summary

In this notebook, I learned how to:

- Detect missing values using `isna()`
- Remove missing values using `dropna()`
- Fill missing values using `fillna()`
- Detect duplicate rows
- Remove duplicates
- Rename columns
- Change data types using `astype()`