In [ ]:
# Grouping & Aggregation

In this notebook, I learn how to group data and calculate statistics for each group.

## Topics
- groupby()
- count()
- sum()
- mean()
- max()
- min()
- agg()

In [1]:
import pandas as pd

df = pd.read_csv("students.csv")
df

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [ ]:
# What is groupby()?
groupby("column's name") divides the dataset into groups based on a column, then lets you perform calculations on each group.

In [3]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")
# This will create groups but doesn't display results

In [ ]:
If I want to Count Students in Each City

In [4]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City").count()

            Name  Age  Grade
City
Alexandria     2    2      2
Cairo          2    2      2
Giza           1    1      1

In [6]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")["Name"].count()
# count name only

City
Alexandria    2
Cairo         2
Giza          1
Name: Name, dtype: int64

In [ ]:
If I want Average Grade in Each City

In [7]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")["Grade"].mean()

City
Alexandria    89.0
Cairo         88.0
Giza          95.0
Name: Grade, dtype: float64

In [ ]:
If I want Highest Grade in Each City

In [8]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")["Grade"].max()

City
Alexandria    90
Cairo         91
Giza          95
Name: Grade, dtype: int64

In [ ]:
If I want Lowest Grade in Each City

In [9]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")["Grade"].min()

City
Alexandria    88
Cairo         85
Giza          95
Name: Grade, dtype: int64

In [ ]:
If I want Total Grade in Each City

In [10]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")["Grade"].sum()

City
Alexandria    178
Cairo         176
Giza           95
Name: Grade, dtype: int64

In [ ]:
If I want Multiple Statistics Using agg()

In [11]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("City")["Grade"].agg(["count", "mean", "max", "min", "sum"])

            count  mean  max  min  sum
City
Alexandria      2  89.0   90   88  178
Cairo           2  88.0   91   85  176
Giza            1  95.0   95   95   95

In [ ]:
If I want Group by Another Column

In [13]:
import pandas as pd

df = pd.read_csv("students.csv")
df.groupby("Name")["Age"].mean()

Name
Ali        20.0
Mona       22.0
Omar       19.0
Sara       21.0
Youssef    20.0
Name: Age, dtype: float64

In [ ]:
# So groupby() means:
Split the data into groups → Apply a calculation to each group → Return the result.

In [ ]:
## Summary

In this notebook, I learned how to:

- Group data using `groupby()`
- Count values
- Calculate the mean
- Find the maximum
- Find the minimum
- Calculate the sum
- Use `agg()` to apply multiple statistics at once