# Merging & Exporting Data

In this notebook, I learn how to combine multiple datasets and export the final results.

## Topics
- concat()
- merge()
- join()
- to_csv()
- to_excel()

In [2]:
import pandas as pd 

student = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Basmala", "Tasneem", "Mariam"],
})

grade = pd.DataFrame({
    "ID": [1, 2, 3],
    "Grade": [90,75,88]
})

student

   ID     Name
0   1  Basmala
1   2  Tasneem
2   3   Mariam

In [3]:
grade

   ID  Grade
0   1     90
1   2     75
2   3     88

<!-- Concatenate DataFrames -->
Concatenate means placing DataFrames on top of each other or side by side.

 # pd.concat()
 <!-- Vertical -->

In [5]:
pd.concat([student, grade])

   ID     Name  Grade
0   1  Basmala    NaN
1   2  Tasneem    NaN
2   3   Mariam    NaN
0   1      NaN   90.0
1   2      NaN   75.0
2   3      NaN   88.0

In [6]:
pd.concat([student, grade], axis=1)
# Horizontal

   ID     Name  ID  Grade
0   1  Basmala   1     90
1   2  Tasneem   2     75
2   3   Mariam   3     88

<!-- Merge DataFrames -->
Merge combines DataFrames using a common column.

In [7]:
merged = pd.merge(student, grade, on="ID")

merged

   ID     Name  Grade
0   1  Basmala     90
1   2  Tasneem     75
2   3   Mariam     88

<!-- Join DataFrames -->
Set the index first:

In [9]:
students = student.set_index("ID")
grades = grade.set_index("ID")

students.join(grades)

       Name  Grade
ID
1   Basmala     90
2   Tasneem     75
3    Mariam     88

In [ ]:
merged.to_csv("students_report.csv", index=False)
# This creates a CSV file in your current folder

In [ ]:
merged.to_excel("students_report.xlsx", index=False)
# This creates an Excel file.
# If you get an error saying that an Excel writer engine is missing, you can install the required package later (such as openpyxl).

## Summary

In this notebook, I learned how to:

- Combine DataFrames using `concat()`
- Merge DataFrames using `merge()`
- Join DataFrames using `join()`
- Export data to CSV
- Export data to Excel