In [ ]:
What is Pandas?

Pandas is a Py library used to:
- Read datasets
- Organize data 
- Clean data 
- Analysis data 
- Prepare data for ML 

It mainly provides 2 data structure: 

__Series__
A one-dimensional data structure(like a single column)

In [2]:
import pandas as pd 

grades = pd.Series([50,69,90,34,85])
print(grades)

0    50
1    69
2    90
3    34
4    85
dtype: int64

In [ ]:
__DataFrame__
A two-dimensional table with rows and columns

In [6]:
import pandas as pd

students = {
      "Names": ["Basmala", "Tasneem", "Mariam"],
      "Grades": [95, 55,87],
      "Ages": [19, 14, 9]
}

df = pd.DataFrame(students)
print(df)

     Names  Grades  Ages
0  Basmala      95    19
1  Tasneem      55    14
2   Mariam      87     9

In [ ]:
To define a dataframe's shape (rows, columns)

In [7]:
import pandas as pd

students = {
      "Names": ["Basmala", "Tasneem", "Mariam"],
      "Grades": [95, 55,87],
      "Ages": [19, 14, 9]
}

df = pd.DataFrame(students)
print(df.shape)

(3, 3)

In [ ]:
To define a dataframe's size

In [8]:
import pandas as pd

students = {
      "Names": ["Basmala", "Tasneem", "Mariam"],
      "Grades": [95, 55,87],
      "Ages": [19, 14, 9]
}

df = pd.DataFrame(students)
print(df.size)

9

In [ ]:
To define a dataframe's columns

In [9]:
import pandas as pd

students = {
      "Names": ["Basmala", "Tasneem", "Mariam"],
      "Grades": [95, 55,87],
      "Ages": [19, 14, 9]
}

df = pd.DataFrame(students)
print(df.columns)

Index(['Names', 'Grades', 'Ages'], dtype='object')

In [ ]:
To define dataframe's index

In [10]:
import pandas as pd

students = {
      "Names": ["Basmala", "Tasneem", "Mariam"],
      "Grades": [95, 55,87],
      "Ages": [19, 14, 9]
}

df = pd.DataFrame(students)
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [ ]:
start = 0 
stop = 3 (from 0 to 2)
step = 1 (increases by 1)

In [ ]:
To define a dataframe's data type

In [11]:
import pandas as pd

students = {
      "Names": ["Basmala", "Tasneem", "Mariam"],
      "Grades": [95, 55,87],
      "Ages": [19, 14, 9]
}

df = pd.DataFrame(students)
print(df.dtypes)

Names     object
Grades     int64
Ages       int64
dtype: object

In [ ]:
To read a csv file

In [17]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()
df.head() 
# exploring data by head()

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [18]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()
df.tail() 
# exploring data by tail() --> show the last 5 rows

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [19]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()
df.tail(2) 
# exploring the last 2 tails()

      Name  Age  Grade        City
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [20]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()
df.sample() 
# shows a random sample()

   Name  Age  Grade        City
3  Mona   22     88  Alexandria

In [21]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()
df.info() 
# Displays info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Grade   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [22]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()
df.describe() 
# Shows statistics for numeric columns

             Age      Grade
count   5.000000   5.000000
mean   20.400000  89.800000
std     1.140175   3.701351
min    19.000000  85.000000
25%    20.000000  88.000000
50%    20.000000  90.000000
75%    21.000000  91.000000
max    22.000000  95.000000

In [24]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df["Grade"]
# to select a specific column

0    90
1    85
2    95
3    88
4    91
Name: Grade, dtype: int64

In [26]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df[["Grade", "Name"]]
# to select specific columns

   Grade     Name
0     90      Ali
1     85     Sara
2     95     Omar
3     88     Mona
4     91  Youssef

In [28]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df.loc[1]
# to select a specific row by index

Name      Sara
Age         21
Grade       85
City     Cairo
Name: 1, dtype: object

In [29]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df.iloc[2]
# to select a specific row by position

Name     Omar
Age        19
Grade      95
City     Giza
Name: 2, dtype: object

In [30]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df[df["Grade"]> 90]
# select rows based on conditions

      Name  Age  Grade   City
2     Omar   19     95   Giza
4  Youssef   20     91  Cairo

In [33]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df[(df["Grade"]> 90) & df["Age"] < 19]
# select rows based on multiple conditions

      Name  Age  Grade        City
0      Ali   20     90  Alexandria
1     Sara   21     85       Cairo
2     Omar   19     95        Giza
3     Mona   22     88  Alexandria
4  Youssef   20     91       Cairo

In [35]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df.sort_values("Grade")
# ascending sort

      Name  Age  Grade        City
1     Sara   21     85       Cairo
3     Mona   22     88  Alexandria
0      Ali   20     90  Alexandria
4  Youssef   20     91       Cairo
2     Omar   19     95        Giza

In [36]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df.sort_values("Grade", ascending = False)
# dscending sort

      Name  Age  Grade        City
2     Omar   19     95        Giza
4  Youssef   20     91       Cairo
0      Ali   20     90  Alexandria
3     Mona   22     88  Alexandria
1     Sara   21     85       Cairo

In [38]:
import pandas as pd 

df = pd.read_csv("students.CSV")
# load a csv file by read_csv()

df.value_counts("Grade")
# counting values

Grade
85    1
88    1
90    1
91    1
95    1
Name: count, dtype: int64